### ISSUE TITLE
Keyboard Nav Issues

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/coulombs-law#94] opened 2018-12-07 19:43 UTC
For https://github.com/phetsims/QA/issues/235 when testing keyboard navigation it was discovered that the esc button does not exit a dialogue as it should. This can be seen by opening the keyboard navigation menu and attempting to exit using the esc button. Another issue that was found is that enter can be used to select any selectable area apart from the "Force Values" and "Scientific Notation" buttons. While the space button can be used to select these options the fact that the enter button can be used for everything else might cause some confusion among users.

**Comment by arouinfar** [comment] 2018-12-07 20:18
> esc button does not exit a dialogue as it should

@JRomero0613 what platform were you testing on? Can you reproduce on other browsers/platforms?   Esc is working correctly for me in macOS 10.13.6/Chrome, so long as the focus is on the close button. If you open the dialog with a mouse, you'll need to first press tab to get focus on the exit button before esc works.

> Another issue that was found is that enter can be used to select any selectable area apart from the "Force Values" and "Scientific Notation" buttons. 

Good observation @JRomero0613. Checkboxes are only selectable with space, not enter. This is standard keyboard behavior for checkboxes that regular keyboard navigation users would be accustomed to. While it's true that space and enter are sometimes redundant, it's not always the case. You can read more about it here: https://github.com/phetsims/coulombs-law/issues/69#issuecomment-428681749

**Comment by arouinfar** [comment] 2018-12-10 20:58
@KatieWoe can you reproduce this issue?

**Comment by KatieWoe** [comment] 2018-12-10 20:59
I can try, but it would be helpful to know what device it was on.  I'll ask @JRomero0613 on slack.

**Comment by JRomero0613** [comment] 2018-12-10 21:08
@arouinfar I can't recall which device it was for certain but it was either macOS 10.13 on all browsers or Windows 10 on all browsers. I'm pretty sure it was Windows 10 as I just tried on a Windows 10 device (desktop) and the esc button does not exit the keyboard navigation menu. As an additional note if the "x" button in the top right corner on the keyboard navigation menu is highlighted by using tab the esc button will exit the menu, otherwise it will not. Not sure if this is the intended behavior or not.

**Comment by arouinfar** [comment] 2018-12-10 22:40
Thanks @JRomero0613.

> As an additional note if the "x" button in the top right corner on the keyboard navigation menu is highlighted by using tab the esc button will exit the menu, otherwise it will not. Not sure if this is the intended behavior or not.

 The esc key is only meant to exit the dialog if the focus (magenta rectangle) is on the dialog's close button. If you opened the dialog with the mouse (or tabbed away from the close button), escape will not close the dialog. 

It sounds like esc exits the dialog so long as the focus is on the close button. If I've understood correctly, please close this issue @JRomero0613.

**Comment by mbarlow12** [comment] 2018-12-12 19:07
@arouinfar Thank you for the comments! @JRomero0613 let me know if you have any further questions. Unassigning myself.

**Comment by arouinfar** [comment] 2018-12-19 20:21
Removed `type:bug` and added `type:wontfix` since I believe @JRomero0613 was encountering intended behavior.

**Comment by arouinfar** [comment] 2018-12-22 22:44
This sim has been through a few additional rounds of QA testing since this issue was first reported, and no issues were reported with closing the keyboard dialog. 

I am fairly confident that @JRomero0613 was encountering the intended behavior (esc only closes dialog when keyboard focus is on the close button), so closing.

**Closed as completed by arouinfar** 2018-12-22 22:44 UTC
Labels: type:wontfix
