### ISSUE TITLE
CT cannot read property get of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#118] opened 2020-06-03 14:50 UTC
```
coulombs-law : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at gM.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:2227416)
at gM.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1058918)
at gM.handleBlur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1058795)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:540239)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:540438)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:539980)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:535282)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:530254
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:61616)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187724683%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:532474)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM

----------------------------------

coulombs-law : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at gM.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:2227416)
at gM.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1058918)
at gM.handleKeyUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1058071)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:540239)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:540438)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:539980)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:535282)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:532068
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:61616)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591191783922%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:532474)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM

----------------------------------

coulombs-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591185954641%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at ChargeNode.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/inverse-square-law-common/js/view/ISLCObjectNode.js:355:47)
at ChargeNode.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:673:14)
at ChargeNode.handleBlur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:654:16)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1851:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1883:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1809:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1037:12)
at Input.focusoutAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:592:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:740:30)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM

----------------------------------

coulombs-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192094423%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at ChargeNode.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/inverse-square-law-common/js/view/ISLCObjectNode.js:355:47)
at ChargeNode.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:673:14)
at ChargeNode.handleKeyUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:558:20)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1851:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1883:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1809:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1037:12)
at Input.keyupAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:711:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:740:30)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM
```

**Comment by zepumph** [comment] 2020-06-03 18:09
Looks to be a duplicate of https://github.com/phetsims/gravity-force-lab/issues/267. Closing

**Closed as completed by zepumph** 2020-06-03 18:09 UTC
Labels: type:automated-testing
