### ISSUE TITLE
Text goes off screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#84] opened 2018-11-27 21:36 UTC
**Device**
iPad Air 2
**OS**
iOS 12
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/221.  When strings are long the "force on q by q" strings can be forced off screen.  This can be seen without an iPad by using both stringTest=double and dev query parameters.
**Steps to Reproduce**
1. Set stringTest=double
2. Go to Atomic Scale and make sure scientific notation is on.  (Occurs on other screen with other settings, but this was how it was discovered.
3. Drag the figure on the left all the way to the left.  Note how the string is off screen.
4. Move the figure on the right.  Note how the left string corrects itself.

**Screenshot**
![img_1341](https://user-images.githubusercontent.com/41024075/49113069-c3707500-f251-11e8-8c64-310ad8e2e943.PNG)

**Comment by KatieWoe** [comment] 2018-11-27 21:45
Note: Can occur with stringTest=long and the movement of the figure to the left must be done quickly.

**Comment by arouinfar** [comment] 2018-11-27 21:48
Nice find @KatieWoe.  Generally speaking, the strings should never escape the `?dev` boundary. 

I've also noticed that the 10 pm scale bar can escape `?dev`. While it's unlikely that pm would get internationalized, let alone translated into 5+ characters, I would think that @mbarlow12 could set an appropriate maxWidth to keep this string on screen.
![image](https://user-images.githubusercontent.com/8419308/49113627-4514d280-f253-11e8-9fba-d85f3fbebed2.png)

**Comment by rea-laura** [comment] 2018-12-07 16:19
@mbarlow12 
Problem mostly fixed but still occurs in https://github.com/phetsims/QA/issues/235. Works fine if figure is moved _slowly_, but will still happen is figure is moved _quickly_ off the screen. 

Device:
Magnus

Browser: 
Safari 11.1.2
Firefox 63.0.3

To Replicate:
1) open sim with ?stringTest=double.
2) go to atomic scale
3) ensure scientific notation is on
4) resize safari window until sim just starts to scale down (we want the window bounds to be at exactly the sim boundaries)
5) drag the left figure _quickly_ to the left edge of the screen
6) the force text will go off the screen, but will fix itself as soon as the right hand figure is moved.

Details:
Also found in Windows 7 Chrome and IE 11
This issue happens with both the left and right hand figures.

**Comment by arouinfar** [comment] 2018-12-07 19:05
@mbarlow12 I observed what @rea-laura describes in macOS 10.13.6/latest Chrome. I compared to the published version of GFL, and the issue is not present there.

I can get the string to go off-screen on Macro Scale and Atomic Scale. The issue can occur whether or not Force Values or Scientific Notation is on, so long as `?stringTest=double` is used. I cannot, however, get the string to go off-screen without using `?stringTest=double`.

**Comment by rea-laura** [comment] 2018-12-07 20:56
@mbarlow12 @arouinfar I just reproduced this problem using the ?stringTest=long query parameter on Windows 7 in the most recent chrome and IE. It's trickier to do, and you might have to play a bit with the window size.

**Comment by rea-laura** [comment] 2018-12-20 20:20
For https://github.com/phetsims/QA/issues/243:
Fixing this issue might have lead to another problem.

<b>Issue</b>
Scale bar sizes down when strings are long.

<b>Device and Browser</b>
Leibniz, iOS 12.1
Safari 12.1

<b>Steps to Reproduce</b>
1) open sim. Note that scale bar in the bottom left corner is slightly cut off by edge of screen.
![4fef6541-eec7-46cd-a6b2-8b9f35575dd1](https://user-images.githubusercontent.com/44005544/50308885-e1e51d00-0459-11e9-9de4-84ec0648f022.png)
2) switch to ?stringTest=double. Note that the scale bar is the same size, yet not cut off by the edge of screen.
![3c67f7b6-b800-4b64-9c4b-434a94527ac6](https://user-images.githubusercontent.com/44005544/50308913-faedce00-0459-11e9-8254-490f0e125bc8.png)
3) switch to ?stringTest=long. Note that the scale bar is now much smaller, making it an inaccurate representation of scale!
![4eca36d3-7a50-4845-8f5a-273f7e8844da](https://user-images.githubusercontent.com/44005544/50308910-f32e2980-0459-11e9-9362-9b02bd00873e.png)

**Comment by KatieWoe** [comment] 2018-12-20 20:31
Note for above: I think that part 1 only occurs on the first screen.  Rest still apply.

**Comment by rea-laura** [comment] 2018-12-20 20:36
New find - the shorter the string, the more the scale bar is cut off by window. 
![image](https://user-images.githubusercontent.com/44005544/50309470-3093b680-045c-11e9-8deb-838a44c5424c.png)

**Comment by arouinfar** [comment] 2018-12-20 21:59
It seems like the position of the scale bar depends on the text. The position of the scale bar in rc.6 is 
a few px away from the layoutBounds, which is correct:

![image](https://user-images.githubusercontent.com/8419308/50312983-3ba01400-0467-11e9-9e97-596c8f2d69c8.png)

The scale bar should never move. The text label should be centered above it, and its maxWidth could be something like this (magenta rectangle), which ensures the string is always within the visible bounds.
![image](https://user-images.githubusercontent.com/8419308/50313135-abae9a00-0467-11e9-936d-4b413b587f6c.png)

**Comment by KatieWoe** [comment] 2018-12-20 22:03
The part of this issue that involves the Force value strings getting pushed off screen does seem fixed in 1.0.0-rc.8

**Comment by KatieWoe** [comment] 2018-12-20 22:08
Worse off screen behavior when stringTest is short.  This does appear on both screens.
![worsewithshort](https://user-images.githubusercontent.com/41024075/50313605-2a580700-0469-11e9-954e-720784250082.PNG)

**Comment by arouinfar** [comment] 2018-12-20 22:51
@mbarlow12 I have one more nit-pick about the scale bar.

The scale bar moves when switching screens in rc.8, but that didn't seem to be the case in rc.6. The behavior is rc.6 is desired.

rc.6: same padding between layoutBounds and scale bar
![image](https://user-images.githubusercontent.com/8419308/50315180-e9fb8780-046e-11e9-9f1e-093e32e12e92.png)

![image](https://user-images.githubusercontent.com/8419308/50315144-c9cbc880-046e-11e9-93fc-deda02078436.png)


rc.8: inconsistent padding between layoutBounds and scale bar

![image](https://user-images.githubusercontent.com/8419308/50315163-d8b27b00-046e-11e9-979f-fcae76c8e5fe.png)
![image](https://user-images.githubusercontent.com/8419308/50315170-dfd98900-046e-11e9-97e1-3042969862c4.png)

**Comment by mbarlow12** [comment] 2018-12-20 22:55
@arouinfar thanks for the clarification. After slowing down a bit, I believe I have the proper solution that both aligns the legend and label and ensures they have consistent spacing from the dev bounds.

Fixed in master and I'm working on prepping the new RC.

**Comment by arouinfar** [comment] 2018-12-22 22:11
Looks great in rc.9!

**Closed as completed by arouinfar** 2018-12-22 22:11 UTC
Labels: type:bug, type:i18n
